### ISSUE TITLE
Add Vulkan support

### ISSUE THREAD

**Issue by pkstDev** [SkyDeckAGoGo/bta-issues#161]
**Is your feature request related to a problem? Please describe.**
nope i guess

**Describe the solution you'd like**
Add option to use Vulkan instead of OpenGL to render.
This should be a very hard task, but it should give great performance improvement.
It can be put off until 1.7.8.0, 1.7.9.0 or even 1.7.114514.0, or can just be declined if you don't have the time or don't want to implement this feature. I don't give much hope to see it implemented into the game.

**Describe alternatives you've considered**
Switch to Vulkan, I think?

**Additional context**
nope

**Comment by Joe4422** [comment]
So the upgrade path here is pretty obvious - we migrate from LWJGL 2 to LWJGL 3, which provides support for Vulkan.

_However,_ I think you're drastically overestimating how much of a performance boost doing so would actually give us - Minecraft's renderer was relatively fast even in 2010, and with 12 years of advancement in GPU technology it's even better. What hurts performance isn't the efficiency of the GPU, or what rendering API it uses - it's that the game is primarily single-threaded. Virtually every single operation in the game, including all the expensive ones such as saving, loading, terrain generation, lighting calculations, and indeed rendering, are all performed on a single main thread.

The solution to performance is to move as much of this workload as possible onto multiple threads; that way, if for example terrain generation stutters, it doesn't impact the performance of the rendering thread, and gameplay continues as smoothly as ever. We're already taking steps to address this - chunk saving and loading will be moved onto a different thread at some point in the 1.7.7.x release cycle, and since I/O operations are particularly expensive, this should result in a significant boost to the overall framerate stability.

As for supporting Vulkan, it could well happen one day, but only if we've exhausted all other opportunities to improve performance, since it would be a significant undertaking with no guaranteed improvements.
